server.port=8080

spring.datasource.url=jdbc:mariadb://database-1.c566c2wauypj.ap-south-1.rds.amazonaws.com:3306/student_db?sslMode=trust
spring.datasource.username=admin
spring.datasource.password=aditya123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

